name: Deploy to Snowflake with Schemachange

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy Dev Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange for Dev
        run: |
          schemachange --verbose -f envs/dev -c schemachange-config/config-dev.yml

  deploy-test:
    name: Deploy Test Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange for Test
        run: |
          schemachange --verbose -f envs/test -c schemachange-config/config-test.yml

  deploy-prod:
    name: Deploy Prod Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange for Prod
        run: |
          schemachange --verbose -f envs/prod -c schemachange-config/config-prod.yml
