name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to DEV
        run: |
          snowflake-cli deploy --config-path configs/config-dev.yml

      - name: Deploy to TEST
        run: |
          snowflake-cli deploy --config-path configs/config-test.yml

      - name: Deploy to PROD
        run: |
          snowflake-cli deploy --config-path configs/config-prod.yml
